[pytest]
# Настройка Allure
addopts = -v --alluredir=allure-results --clean-alluredir

# Путь к тестам
testpaths = .

# Python path
pythonpath = .

# Маркеры
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')